#!/bin/sh

# List of parameters

RECURSIVE=0
SUBDIRECTORIES=0
LOWERCASE=0
UPPERCASE=0
LIST_OF_FILE=""

INPUT=""
OUTPUT=""

INIT_DIR=$(pwd)

help_msg(){
    # Print the following help message
    echo "Usage: script_name [OPTIONS] [FILENAMES]"

    echo "Options:"
    echo "  -r, --recursive            Process directories recursively."
    echo "  -s, --subdirectories       Process subdirectories as well."
    echo "  -l, --lowercase            Convert filenames to lowercase."
    echo "  -u, --uppercase            Convert filenames to uppercase."
    echo "  -h, --help                 Display this help message."

    echo "Example:"
    echo "  script_name -r -l file1.txt directory1"
}

to_upper(){
    # Convert input variable to uppercase and store it in OUTPUT
    OUTPUT=$(echo $1 | tr '[:lower:]' '[:upper:]')
}

to_lower(){
    # Convert input variable to lowercase and store it in OUTPUT
    OUTPUT=$(echo $1 | tr '[:upper:]' '[:lower:]')
}

get_args(){
    #Parse the parameter passed in input
    case "$1" in
        -r|--recursive) RECURSIVE=1;;
        -s|--subdirectories) SUBDIRECTORIES=1;;
        -l|--lowercase) LOWERCASE=1;;
        -u|--uppercase) UPPERCASE=1;;
        -h|--help) help_msg && exit;;
        *) LIST_OF_FILE="$1 $LIST_OF_FILE"
    esac
}

change_name(){
    FILEPATH=""
    if [[ "$INPUT" == *\/* ]];then
        # If the name contains "/" for example folder/subfolder/file
        # Cut the name in two part, the path and the name of the file
        FILEPATH="$(echo $INPUT | sed 's:/[^/]*$::')/"
        INPUT=$(echo $INPUT | sed 's:.*/::')
    fi
    if [ $UPPERCASE -eq 1 ];then
        to_upper $INPUT
    else
        to_lower $INPUT
    fi
    # Reformat file names
    INPUT=$FILEPATH$INPUT
    OUTPUT=$FILEPATH$OUTPUT
}

main_func(){
while test "x$1" != "x";do 
    if [ -d $1 ]; then
        # If the file is a directory
        if [ $RECURSIVE -eq 1 ];then
            # If recursive is active, cd in the directory 
            # and apply this function to all files int the directory
            local PREV_DIR=$(pwd)
            cd $1
            main_func $(ls)
            cd $PREV_DIR
            # Get back to the parent directory
        fi
        if [ $SUBDIRECTORIES -eq 1 ];then
            # If subdirectories is active, 
            # change the name of the directory
            INPUT=$1
            change_name
            mv $INPUT $OUTPUT 2>/dev/null
        fi
    elif [ -f $1 ]; then
        INPUT=$1
        change_name
        mv $INPUT $OUTPUT 2>/dev/null
    else
        echo "ERROR : $1 doesn't exist"
    fi
    shift
done
}

# Parse all args one by one
while test "x$1" != "x";do
    get_args $1
    shift
done

# Error handling
if [[ $UPPERCASE -eq 1 && $LOWERCASE -eq 1 ]];then
    echo "ERROR : CAN'T LOWERCASE AND UPPERCASE"
    exit
fi  
if [[ $UPPERCASE -eq 0 && $LOWERCASE -eq 0 ]];then
    echo "ERROR : CAN'T DO NOTHING"
    exit
fi  


main_func $LIST_OF_FILE
cd $INIT_DIR
